CREATE TABLE socialmedia.comments (
    comment_id VARCHAR(255) NOT NULL,
    comment VARCHAR(255),
    post_id INTEGER NOT NULL,
    user_id VARCHAR(255),
    PRIMARY KEY (comment_id)
);

CREATE TABLE socialmedia.likes (
    like_id VARCHAR(255) NOT NULL,
    post_id INTEGER NOT NULL,
    user_id VARCHAR(255),
    PRIMARY KEY (like_id)
);

CREATE TABLE socialmedia.posts (
    post_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    created_on TIMESTAMP(6) WITH TIME ZONE,
    image_url VARCHAR(255),
    post_text VARCHAR(255),
    total_comments INTEGER NOT NULL,
    total_likes INTEGER NOT NULL,
    user_id VARCHAR(255),
    PRIMARY KEY (post_id)
);

CREATE TABLE socialmedia.save (
    save_post_id VARCHAR(255) NOT NULL,
    created_on TIMESTAMP(6) WITH TIME ZONE,
    post_id INTEGER NOT NULL,
    user_id VARCHAR(255),
    PRIMARY KEY (save_post_id)
);

CREATE TABLE socialmedia.users_tbl (
    user_id VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    password VARCHAR(255),
    PRIMARY KEY (user_id)
);

    alter table if exists socialmedia.posts
       add constraint FKmxk8mmhmidvoaso6ou8je2mie
       foreign key (user_id)
       references socialmedia.profiles